repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: 'package-lock\.json$'  # Exclude package-lock.json files

  - repo: local
    hooks:
      - id: sync-metadata
        name: Sync metadata from __init__.py to pyproject.toml
        entry: bash -c 'cd backend && source venv/bin/activate && netwiz-sync-metadata --check || (netwiz-sync-metadata && echo "Metadata synced successfully" && exit 1)'
        language: system
        files: ^backend/netwiz_backend/__init__.py$
        pass_filenames: false
        always_run: true
