version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: netwiz-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - netwiz-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: netwiz-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Environment Configuration
      - ENVIRONMENT=production
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=5000
      - RELOAD=false
      - LOG_LEVEL=INFO

      # Database Configuration
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/netwiz?authSource=admin
      - MONGODB_DATABASE=netwiz

      # CORS Configuration
      - CORS_ORIGINS=*

      # API Configuration
      - API_PREFIX=/api
      - DOCS_URL=/docs
      - REDOC_URL=/redoc
    depends_on:
      - mongodb
    networks:
      - netwiz-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: netwiz-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - netwiz-network

volumes:
  mongodb_data:

networks:
  netwiz-network:
    driver: bridge
