version: '3.8'

# NetWiz Production Deployment
# This file allows users to run NetWiz without cloning the repository
# Just download this file and run: docker-compose -f docker-compose.prod.yml up

services:
  backend:
    image: ghcr.io/modularizer/netwiz-backend:latest
    container_name: netwiz-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=5000
      - MONGODB_URI=mongodb://${MONGODB_USER:-admin}:${MONGODB_PASSWORD:-password}@mongodb:27017/netwiz?authSource=admin
      - MONGODB_DATABASE=netwiz
      - CORS_ORIGINS=https://modularizer.github.io,https://modularizer.github.io/NetWiz,http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - netwiz-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:7.0
    container_name: netwiz-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-password}
    volumes:
      - ${MONGODB_DATA_PATH:-mongodb_data}:/data/db
    networks:
      - netwiz-network

volumes:
  mongodb_data:
    external: false

networks:
  netwiz-network:
    driver: bridge
