version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: netwiz-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - netwiz-dev-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: netwiz-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    environment:
      # Override specific variables for development
      - ENVIRONMENT=development
      - DEBUG=true
      - RELOAD=true
      - LOG_LEVEL=DEBUG
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/netwiz?authSource=admin
    depends_on:
      - mongodb
    networks:
      - netwiz-dev-network
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: netwiz-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - netwiz-dev-network
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_dev_data:

networks:
  netwiz-dev-network:
    driver: bridge
