version: '3.8'

# Production deployment using GitHub Pages for frontend
# This assumes your frontend is deployed to GitHub Pages at:
# https://${GITHUB_USER:-modularizer}.github.io/${GITHUB_PROJECT:-NetWiz}/

services:
  backend:
    image: ghcr.io/${GITHUB_USER:-modularizer}/${GITHUB_PROJECT:-netwiz}-backend:latest
    container_name: netwiz-backend-prod
    restart: "no"
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - HOST=0.0.0.0
      - PORT=${BACKEND_PORT:-5000}
      - MONGODB_URI=mongodb://${MONGODB_USER:-admin}:${MONGODB_PASSWORD:-password}@mongodb:27017/netwiz?authSource=admin
      - MONGODB_DATABASE=netwiz
      # CORS for GitHub Pages
      - CORS_ORIGINS=https://${GITHUB_USER:-modularizer}.github.io,https://${GITHUB_USER:-modularizer}.github.io/${GITHUB_PROJECT:-NetWiz},http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - netwiz-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-5000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:7.0
    container_name: netwiz-mongodb-prod
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-password}
    volumes:
      - ${MONGODB_DATA_PATH:-mongodb_data}:/data/db
    networks:
      - netwiz-network

volumes:
  mongodb_data:
    external: false

networks:
  netwiz-network:
    driver: bridge
