version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: netwiz-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - netwiz-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: netwiz-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/netwiz?authSource=admin
    depends_on:
      - mongodb
    networks:
      - netwiz-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: netwiz-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - netwiz-network

volumes:
  mongodb_data:

networks:
  netwiz-network:
    driver: bridge
