version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: netwiz-mongodb
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-password}
    volumes:
      - ${MONGODB_DATA_PATH:-mongodb_data}:/data/db
    networks:
      - netwiz-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT:-production}
    container_name: netwiz-backend
    restart: "no"
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - HOST=0.0.0.0
      - PORT=${BACKEND_PORT:-5000}
      - MONGODB_URI=mongodb://${MONGODB_USER:-admin}:${MONGODB_PASSWORD:-password}@mongodb:27017/netwiz?authSource=admin
      - MONGODB_DATABASE=netwiz
      - CORS_ORIGINS=http://frontend:${FRONTEND_PORT:-3000},http://localhost:${FRONTEND_PORT:-3000}

    depends_on:
      - mongodb
    networks:
      - netwiz-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: netwiz-frontend
    restart: "no"
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    environment:
      - NODE_ENV=${ENVIRONMENT:-production}
      - PORT=${FRONTEND_PORT:-3000}
      - VITE_API_BASE_URL=/api
      - REACT_APP_API_BASE_URL=/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - netwiz-network

volumes:
  mongodb_data:
    external: false

networks:
  netwiz-network:
    driver: bridge
