name: Build and Push Backend Container

on:
  pull_request:
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: modularizer/netwiz-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run unit tests
      run: |
        cd backend
        pytest tests/unit/ -v --cov=netwiz_backend --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: backend-unit
        name: backend-coverage
        fail_ci_if_error: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Get git metadata
      id: git
      run: |
        echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "commit_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
        echo "tag=$(git describe --tags --exact-match 2>/dev/null || echo '')" >> $GITHUB_OUTPUT
        echo "build_time=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
        echo "build_ref=${{ github.ref }}" >> $GITHUB_OUTPUT
        echo "build_sha=${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Create .env file
      run: |
        cat > .env << EOF
        ENVIRONMENT=production
        FRONTEND_PORT=3000
        BACKEND_PORT=5000
        MONGODB_USER=admin
        MONGODB_PASSWORD=password
        EOF

    - name: Build and push testing image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          ENVIRONMENT=production
          GIT_COMMIT_HASH=${{ steps.git.outputs.commit_hash }}
          GIT_COMMIT_SHORT=${{ steps.git.outputs.commit_short }}
          GIT_BRANCH=${{ steps.git.outputs.branch }}
          GIT_TAG=${{ steps.git.outputs.tag }}
          BUILD_TIME=${{ steps.git.outputs.build_time }}
          BUILD_REF=${{ steps.git.outputs.build_ref }}
          BUILD_SHA=${{ steps.git.outputs.build_sha }}

    - name: Test Docker image
      if: github.event_name != 'pull_request'
      run: |
        # Test that the image can be pulled and run
        docker pull ${{ steps.meta.outputs.tags }}

        # Test basic container startup with more robust configuration
        CONTAINER_ID=$(docker run -d \
          -e MONGODB_URI=mongodb://test:test@localhost:27017/test \
          -e MONGODB_DATABASE=test \
          -e CORS_ORIGINS=* \
          -e PORT=5000 \
          -e ENVIRONMENT=production \
          -e JWT_SECRET_KEY=test-secret-key \
          -e JWT_REFRESH_SECRET_KEY=test-refresh-secret-key \
          -e PASSWORD_PEPPER=test-pepper \
          --memory=512m \
          --cpus=1 \
          -p 5000:5000 \
          ${{ steps.meta.outputs.tags }})

        echo "Container ID: $CONTAINER_ID"
        echo "Waiting for container to start..."

        # Wait for container to start with better logging
        for i in {1..10}; do
          echo "Attempt $i: Checking container status..."
          if docker ps | grep -q $CONTAINER_ID; then
            echo "✅ Container is running"
            break
          else
            echo "❌ Container not running, attempt $i"
            if [ $i -eq 10 ]; then
              echo "❌ Container failed to start after 10 attempts"
              echo "Container logs:"
              docker logs $CONTAINER_ID
              docker rm $CONTAINER_ID
              exit 1
            fi
            sleep 10
          fi
        done

        # Wait additional time for application startup
        echo "Waiting for application to start..."
        sleep 5

        # Check container logs
        echo "Container logs:"
        docker logs $CONTAINER_ID

        # Test health endpoint with retries
        echo "Testing health endpoint..."
        for i in {1..5}; do
          echo "Health check attempt $i..."
          if curl -f --connect-timeout 10 --max-time 30 http://localhost:5000/health; then
            echo "✅ Health endpoint is responding"
            break
          else
            echo "❌ Health endpoint not responding, attempt $i failed"
            if [ $i -eq 5 ]; then
              echo "❌ Health endpoint failed after 5 attempts"
              echo "Container logs:"
              docker logs $CONTAINER_ID
              echo "Port binding check:"
              docker port $CONTAINER_ID
              echo "Process check:"
              docker exec $CONTAINER_ID ps aux || echo "Cannot exec into container"
              docker stop $CONTAINER_ID
              docker rm $CONTAINER_ID
              exit 1
            fi
            sleep 2
          fi
        done

        # Test root endpoint includes git metadata
        ROOT_RESPONSE=$(curl -s http://localhost:5000/)
        echo "Root endpoint response: $ROOT_RESPONSE"
        echo "$ROOT_RESPONSE" | jq -e '.git' || echo "Warning: Git metadata not found in root endpoint"

        # Test API info endpoint
        curl -f http://localhost:5000/info || exit 1

        # Test OpenAPI endpoint
        curl -f http://localhost:5000/openapi.json || exit 1

        pytest tests/integration/ -v

        # Clean up
        docker stop $CONTAINER_ID
        docker rm $CONTAINER_ID

        echo "✅ All integration tests passed!"

    - name: Promote to latest
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      run: |
        # Get the main branch tag (which is our testing tag)
        MAIN_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main"
        LATEST_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"

        echo "Promoting $MAIN_TAG to $LATEST_TAG"

        # Pull the main branch image
        docker pull $MAIN_TAG

        # Tag as latest
        docker tag $MAIN_TAG $LATEST_TAG

        # Push the latest tag
        docker push $LATEST_TAG

        echo "✅ Successfully promoted to latest tag: $LATEST_TAG"
